#%RAML 1.0
title: customer-api

/customers:
  get:
    responses:
      200:
        body:
          application/json:
            example:
               [{"name":"srinu"},{"name":"Ramu"}]
             
           